version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: node:16
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: scp -oStrictHostKeyChecking=no -r build/* gnosis@178.62.227.183:/var/www/html/
                 
# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - master