name: Deployer
on:
  pull_request_target:
    types:
      - closed
    branches:
      - master
jobs:
  if_merged:
    name: Build Code & Deploy to server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run ESLint
      run: yarn linter    
    - name: Deploy code to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: "build/*"
        target: "/var/www/html/"

